name: GitHub Profile Language Analytics

on:
  schedule:
    - cron: "6 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Language Stats
        uses: xaoccc/Github-Language-Stats@main
        with:
          github_token: ${{ secrets.STATS_TOKEN }}
          visualization_types: "leaderboard bar pie donut"
          exclude_repos: "SEDO-Regular-Exam-2024-10,SeleniumWebDriver"
          include_forks: "false"
          output_path: "stats"
          exclude_languages: "C#,SCSS,HTML,CSS,HCL,Roff"
          dark_mode: "true"
          
# For more info visit https://github.com/marketplace/actions/github-profile-language-analytics
